/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Brian' at '1/30/19 4:18 AM' with Gradle 2.13
 *
 * @author Brian, @date 1/30/19 4:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
